apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  includeCRDs: true
  version: 4.3.0
  namespace: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx